# Generated by Django 2.2.10 on 2020-12-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(db_index=True, verbose_name='amount')),
                ('product_name', models.CharField(db_index=True, max_length=40, verbose_name='product name')),
                ('created_time', models.DateTimeField(db_index=True, verbose_name='creation On')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='modified On')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='year')),
                ('prod1_sales', models.IntegerField(db_index=True, verbose_name='product 1 sales')),
                ('prod2_sales', models.IntegerField(db_index=True, verbose_name='product 2 sales')),
                ('prod3_sales', models.IntegerField(db_index=True, verbose_name='product 3 sales')),
            ],
            options={
                'verbose_name': 'statistic',
                'verbose_name_plural': 'stats',
            },
        ),
    ]
